## 2.1Tensor基础

### 1数学含义

tensor对于pytorch实际上是array对于numpy，这个实际上是多维运算工具，不过是比numpy增加了各式各样的运算方法和函数。

### 2基本创建方法

In [1]:
import torch

In [2]:
x = torch.Tensor(2, 4)  #创建张量
x

tensor([[0.9487, 0.0000, 0.3162, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])

In [3]:
print(x.type())
print(x.dtype)

torch.FloatTensor
torch.float32


tensor一共包含八种数据类型：
<img height="800" src="2-1.jpeg" width="1600"/>

In [4]:
y = torch.DoubleTensor(2, 3, 4)  #两个3x4矩阵
y

tensor([[[ -2.0000e+00, -4.3323e-311,  7.9051e-323,   0.0000e+00],
         [  0.0000e+00,   0.0000e+00,   0.0000e+00,  1.2599e-321],
         [  0.0000e+00,   0.0000e+00,   0.0000e+00,   0.0000e+00]],

        [[ 1.2599e-321,   0.0000e+00,   0.0000e+00,   0.0000e+00],
         [  0.0000e+00,  1.2599e-321,   0.0000e+00,   0.0000e+00],
         [  0.0000e+00,   0.0000e+00,  1.2599e-321,   0.0000e+00]]],
       dtype=torch.float64)

In [5]:
#使用python原生列表进行初始化
list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
torch.Tensor(list)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [6]:
'''
Tensor和tensor大小写不一样
'''
#使用python索引方式获取Tensor中的元素值
x = torch.Tensor([[2, 4, 5], [7, 6, 3]])
x[0][2]

tensor(5.)

In [7]:
#使用索引修改Tensor中的元素
x[0][2] = 9
x

tensor([[2., 4., 9.],
        [7., 6., 3.]])

### 3快速创建方法

In [8]:
torch.zeros(2, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
torch.ones(2, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
torch.rand(2, 4)  #创建[0,1)区间的随机数

tensor([[0.6038, 0.3402, 0.6944, 0.5534],
        [0.6187, 0.9854, 0.6149, 0.5955]])

In [12]:
print(torch.arange(1, 4))
print(torch.arange(1, 4, 0.5))

tensor([1, 2, 3])
tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000])


还有其他创建方法：
<img alt="创建方法" height="800" src="2-2.jpeg" width="1600"/>

### 4常用数学方法
除了常见的加法，乘法和除法还有：
<img alt="常用数学运算" height="800" src="2-3.png" width="1600"/>

In [13]:
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])
b = torch.ones(2, 3)
print(a)
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
print(b.add(a))  #b本身的值不变
print(torch.add(a, b))
print(b.add_(a))  #覆盖加法
print(b)

tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[2., 3., 4.],
        [5., 6., 7.]])


In [15]:
#广播
a = torch.rand(3)
print(a)

print(a + 2)

print(torch.add(a, 2))

print(a.add(2))

tensor([0.5182, 0.4103, 0.1761])
tensor([2.5182, 2.4103, 2.1761])
tensor([2.5182, 2.4103, 2.1761])
tensor([2.5182, 2.4103, 2.1761])


In [16]:
#abs方法
torch.abs(torch.Tensor([[-5, -4, -3], [-3, -2, -1]]))

tensor([[5., 4., 3.],
        [3., 2., 1.]])

In [17]:
#ceil向上取整数
a = torch.Tensor([0.2, 1.5, 3.4])
print(a)
torch.ceil(a)

tensor([0.2000, 1.5000, 3.4000])


tensor([1., 2., 4.])

In [18]:
#exp取指数
torch.exp(torch.Tensor([1, 2, 3]))

tensor([ 2.7183,  7.3891, 20.0855])

In [19]:
torch.max(torch.Tensor([1, 2, 3]))

tensor(3.)

### 5线性代数运算

In [20]:
#dot向量与向量的内积运算
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([2, 3, 4])
torch.dot(a, b)

tensor(20.)

In [21]:
#mv实现矩阵与向量的运算,m代表矩阵，v代表向量
a = torch.Tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
print(a)

b = torch.Tensor([1, 2, 3])
print(b)

torch.mv(a, b)

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])
tensor([1., 2., 3.])


tensor([14., 20., 26.])

In [22]:
#mm将两个矩阵相乘
a = torch.Tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
print(a)

b = torch.Tensor([[2, 3, 4], [3, 4, 5], [4, 5, 6]])
print(b)

torch.mm(a, b)

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])
tensor([[2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])


tensor([[20., 26., 32.],
        [29., 38., 47.],
        [38., 50., 62.]])

还有其他运算:
<img alt="运算" height="800" src="2-4.jpeg" width="1600"/>

### 6连接和切片

In [23]:
#使用cat将多个Tensor沿莫纬度进行连接
a = torch.rand(2, 2)
print(a)

b = torch.rand(2, 2)
print(b)

#在第0纬上进行连接
print(torch.cat((a, b), 0))

#在第2纬上进行连接
print(torch.cat((a, b), 1))

tensor([[0.2487, 0.9406],
        [0.0747, 0.0851]])
tensor([[0.7956, 0.2102],
        [0.9757, 0.8366]])
tensor([[0.2487, 0.9406],
        [0.0747, 0.0851],
        [0.7956, 0.2102],
        [0.9757, 0.8366]])
tensor([[0.2487, 0.9406, 0.7956, 0.2102],
        [0.0747, 0.0851, 0.9757, 0.8366]])


In [24]:
#使用chunk进行切片，有三个参数，一个是切片对象，第二个是切片块数，第三个是切片纬度
c = torch.rand(2, 4)
print(c)

torch.chunk(c, 2, 1)

tensor([[0.3213, 0.8758, 0.7084, 0.0452],
        [0.5449, 0.9661, 0.5191, 0.6263]])


(tensor([[0.3213, 0.8758],
         [0.5449, 0.9661]]),
 tensor([[0.7084, 0.0452],
         [0.5191, 0.6263]]))

In [25]:
#使用t进行转置
a = torch.rand(2, 2)
print(a)

print(torch.t(a))

tensor([[0.0209, 0.8066],
        [0.0727, 0.1312]])
tensor([[0.0209, 0.0727],
        [0.8066, 0.1312]])


还有其他功能：
<img alt="连接切片功能" height="800" src="2-5.jpeg" width="1600"/>

### 7变形

In [26]:
x = torch.rand(2, 3, 4)
print(x)

y = x.view(2, 12)
print(y)

z = x.view(-1, 1)  #使用-1时会自动计算纬度的数目
print(z)
print(z.size())

tensor([[[0.2399, 0.8060, 0.0882, 0.1670],
         [0.9213, 0.9991, 0.1535, 0.3507],
         [0.9141, 0.5708, 0.1600, 0.7916]],

        [[0.4118, 0.1386, 0.2066, 0.0916],
         [0.7211, 0.1697, 0.4663, 0.6033],
         [0.6194, 0.4225, 0.6824, 0.6231]]])
tensor([[0.2399, 0.8060, 0.0882, 0.1670, 0.9213, 0.9991, 0.1535, 0.3507, 0.9141,
         0.5708, 0.1600, 0.7916],
        [0.4118, 0.1386, 0.2066, 0.0916, 0.7211, 0.1697, 0.4663, 0.6033, 0.6194,
         0.4225, 0.6824, 0.6231]])
tensor([[0.2399],
        [0.8060],
        [0.0882],
        [0.1670],
        [0.9213],
        [0.9991],
        [0.1535],
        [0.3507],
        [0.9141],
        [0.5708],
        [0.1600],
        [0.7916],
        [0.4118],
        [0.1386],
        [0.2066],
        [0.0916],
        [0.7211],
        [0.1697],
        [0.4663],
        [0.6033],
        [0.6194],
        [0.4225],
        [0.6824],
        [0.6231]])
torch.Size([24, 1])


### 8使用cuda加速

In [27]:
# 看机器是否支持cuda
torch.cuda.is_available()

False

In [28]:
#对比cpu和gpu运算时间
#coding=utf-8
from time import perf_counter

x = torch.rand(1000, 10000)
y = torch.rand(10000, 10000)

#CPU
start = perf_counter()
x.mm(y)
finish = perf_counter()
time = finish - start
print("CPU计算时间:%s" % time)

#GPU
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    start = perf_counter()
    x.mm(y)
    finish = perf_counter()
    time_cuda = finish - start
    print("GPU加速计算的时间:%s" % time_cuda)
    print("CPU计算时间是GPU加速计算时间的%s倍" % str(time / time_cuda))

else:
    print("未支持CUDA")


CPU计算时间:4.568583255999999
未支持CUDA


## 2.2Autograd
### 1微分示例
pytorch的autograd功能可以自动求导
### 2基本原理
对Tensor变量设置参数即可，requires_grad设置后为True，grad参数会存储微分，grad_fn存储微分函数
### 3前向传播

In [30]:
x = torch.ones(2)
x.requires_grad

False

In [31]:
x.requires_grad = True
x

tensor([1., 1.], requires_grad=True)

In [32]:
print(x.grad)
print(x.grad_fn)

None
None


In [33]:
z = 4 * x
z

tensor([4., 4.], grad_fn=<MulBackward0>)

In [34]:
y = z.norm()
y

tensor(5.6569, grad_fn=<CopyBackwards>)

### 4反向传播

In [42]:
y.backward
x.grad

tensor([2.8284, 2.8284])

In [45]:
#只有末端的节点梯度才会被更新
print(z.grad)
print(y.grad)

None
None


### 5非标量输出
输出是非标量时，使用反向传播要增加一个与输出形状一样的ones

In [48]:
z = torch.ones(2, 1)
X = torch.Tensor([[2, 3], [1, 2]])
X.requires_grad=True

y=X.mm(z)
print(y)

y.backward(torch.ones(2,1))
print(X.grad)

tensor([[5.],
        [3.]], grad_fn=<MmBackward0>)
tensor([[1., 1.],
        [1., 1.]])
