## 2.1Tensor基础

### 1数学含义

tensor对于pytorch实际上是array对于numpy，这个实际上是多维运算工具，不过是比numpy增加了各式各样的运算方法和函数。

### 2基本创建方法

In [1]:
import torch

In [2]:
x = torch.Tensor(2, 4)  #创建张量
x

tensor([[ 0.0000e+00, -4.6566e-10, -2.7624e-20, -1.5849e+29],
        [ 1.0000e+00,  2.0000e+00,  0.0000e+00,  0.0000e+00]])

In [3]:
print(x.type())
print(x.dtype)

torch.FloatTensor
torch.float32


tensor一共包含八种数据类型：
<img height="800" src="2-1.jpeg" width="1600"/>

In [4]:
y = torch.DoubleTensor(2, 3, 4)  #两个3x4矩阵
y

tensor([[[ 0.0000e+00, 1.2599e-321,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00, 1.2599e-321,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00, 1.2599e-321]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [1.2599e-321,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]],
       dtype=torch.float64)

In [5]:
#使用python原生列表进行初始化
list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
torch.Tensor(list)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [6]:
'''
Tensor和tensor大小写不一样
'''
#使用python索引方式获取Tensor中的元素值
x = torch.Tensor([[2, 4, 5], [7, 6, 3]])
x[0][2]

tensor(5.)

In [7]:
#使用索引修改Tensor中的元素
x[0][2] = 9
x

tensor([[2., 4., 9.],
        [7., 6., 3.]])

### 3快速创建方法

In [8]:
torch.zeros(2, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [10]:
torch.ones(2, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
torch.rand(2, 4)  #创建[0,1)区间的随机数

tensor([[0.2831, 0.1272, 0.5737, 0.9028],
        [0.2333, 0.2118, 0.2401, 0.1143]])

In [12]:
print(torch.arange(1, 4))
print(torch.arange(1, 4, 0.5))

tensor([1, 2, 3])
tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000])


还有其他创建方法：
<img alt="创建方法" height="800" src="2-2.jpeg" width="1600"/>

### 4常用数学方法
除了常见的加法，乘法和除法还有：
<img alt="常用数学运算" height="800" src="2-3.png" width="1600"/>

In [13]:
a = torch.Tensor([[1, 2, 3], [4, 5, 6]])
b = torch.ones(2, 3)
print(a)
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
print(b.add(a))  #b本身的值不变
print(torch.add(a, b))
print(b.add_(a))  #覆盖加法
print(b)

tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[2., 3., 4.],
        [5., 6., 7.]])


In [15]:
#广播
a = torch.rand(3)
print(a)

print(a + 2)

print(torch.add(a, 2))

print(a.add(2))

tensor([0.9540, 0.1845, 0.0388])
tensor([2.9540, 2.1845, 2.0388])
tensor([2.9540, 2.1845, 2.0388])
tensor([2.9540, 2.1845, 2.0388])


In [16]:
#abs方法
torch.abs(torch.Tensor([[-5, -4, -3], [-3, -2, -1]]))

tensor([[5., 4., 3.],
        [3., 2., 1.]])

In [17]:
#ceil向上取整数
a = torch.Tensor([0.2, 1.5, 3.4])
print(a)
torch.ceil(a)

tensor([0.2000, 1.5000, 3.4000])


tensor([1., 2., 4.])

In [18]:
#exp取指数
torch.exp(torch.Tensor([1, 2, 3]))

tensor([ 2.7183,  7.3891, 20.0855])

In [19]:
torch.max(torch.Tensor([1, 2, 3]))

tensor(3.)

### 5线性代数运算

In [20]:
#dot向量与向量的内积运算
a = torch.Tensor([1, 2, 3])
b = torch.Tensor([2, 3, 4])
torch.dot(a, b)

tensor(20.)

In [21]:
#mv实现矩阵与向量的运算,m代表矩阵，v代表向量
a = torch.Tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
print(a)

b = torch.Tensor([1, 2, 3])
print(b)

torch.mv(a, b)

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])
tensor([1., 2., 3.])


tensor([14., 20., 26.])

In [22]:
#mm将两个矩阵相乘
a = torch.Tensor([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
print(a)

b = torch.Tensor([[2, 3, 4], [3, 4, 5], [4, 5, 6]])
print(b)

torch.mm(a,b)

tensor([[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]])
tensor([[2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])


tensor([[20., 26., 32.],
        [29., 38., 47.],
        [38., 50., 62.]])

还有其他运算:
<img alt="运算" height="800" src="2-4.jpeg" width="1600"/>

### 6连接和切片

In [23]:
#使用cat将多个Tensor沿莫纬度进行连接
a=torch.rand(2,2)
print(a)

b=torch.rand(2,2)
print(b)

#在第0纬上进行连接
print(torch.cat((a,b),0))

#在第2纬上进行连接
print(torch.cat((a,b),1))

tensor([[0.9139, 0.8218],
        [0.9427, 0.4544]])
tensor([[0.0674, 0.1888],
        [0.6277, 0.3100]])
tensor([[0.9139, 0.8218],
        [0.9427, 0.4544],
        [0.0674, 0.1888],
        [0.6277, 0.3100]])
tensor([[0.9139, 0.8218, 0.0674, 0.1888],
        [0.9427, 0.4544, 0.6277, 0.3100]])


In [24]:
#使用chunk进行切片，有三个参数，一个是切片对象，第二个是切片块数，第三个是切片纬度
c=torch.rand(2,4)
print(c)

torch.chunk(c,2,1)

tensor([[0.8602, 0.0832, 0.7501, 0.3749],
        [0.0413, 0.2082, 0.2783, 0.1865]])


(tensor([[0.8602, 0.0832],
         [0.0413, 0.2082]]),
 tensor([[0.7501, 0.3749],
         [0.2783, 0.1865]]))

In [25]:
#使用t进行转置
a=torch.rand(2,2)
print(a)

print(torch.t(a))

tensor([[0.7594, 0.7030],
        [0.2962, 0.5419]])
tensor([[0.7594, 0.2962],
        [0.7030, 0.5419]])


还有其他功能：
<img alt="连接切片功能" height="800" src="2-5.jpeg" width="1600"/>

### 7变形

In [29]:
x=torch.rand(2,3,4)
print(x)

y=x.view(2,12)
print(y)

z=x.view(-1,1)#使用-1时会自动计算纬度的数目
print(z)
print(z.size())

tensor([[[0.8939, 0.1109, 0.1723, 0.6760],
         [0.5119, 0.5615, 0.8712, 0.6815],
         [0.1948, 0.7902, 0.9133, 0.9729]],

        [[0.2825, 0.1340, 0.0606, 0.5601],
         [0.1417, 0.2061, 0.6101, 0.6111],
         [0.3187, 0.1592, 0.4177, 0.3753]]])
tensor([[0.8939, 0.1109, 0.1723, 0.6760, 0.5119, 0.5615, 0.8712, 0.6815, 0.1948,
         0.7902, 0.9133, 0.9729],
        [0.2825, 0.1340, 0.0606, 0.5601, 0.1417, 0.2061, 0.6101, 0.6111, 0.3187,
         0.1592, 0.4177, 0.3753]])
tensor([[0.8939],
        [0.1109],
        [0.1723],
        [0.6760],
        [0.5119],
        [0.5615],
        [0.8712],
        [0.6815],
        [0.1948],
        [0.7902],
        [0.9133],
        [0.9729],
        [0.2825],
        [0.1340],
        [0.0606],
        [0.5601],
        [0.1417],
        [0.2061],
        [0.6101],
        [0.6111],
        [0.3187],
        [0.1592],
        [0.4177],
        [0.3753]])
torch.Size([24, 1])


### 8使用cuda加速

In [30]:
# 看机器是否支持cuda
torch.cuda.is_available()

False

In [32]:
#对比cpu和gpu运算时间
#coding=utf-8
from time import perf_counter

x = torch.rand(1000,10000)
y = torch.rand(10000,10000)

#CPU
start = perf_counter()
x.mm(y)
finish = perf_counter()
time = finish-start
print("CPU计算时间:%s" % time)

#GPU
if torch.cuda.is_available():
	x = x.cuda()
	y = y.cuda()
	start = perf_counter()
	x.mm(y)
	finish = perf_counter()
	time_cuda = finish-start
	print("GPU加速计算的时间:%s" % time_cuda)
	print("CPU计算时间是GPU加速计算时间的%s倍" % str(time/time_cuda))

else:
	print("未支持CUDA")


CPU计算时间:1.884241553000038
未支持CUDA


## Autograd